### ISSUE TITLE
Add div.AfruxWidgets-Widget-title

### ISSUE THREAD

**Issue by iamdarkle** [justoverclockl/last-registered-users#2]
I think this enhancement could be added to more of your widgets apart from this one (I currently use `justoverclock/last-registered-users` and `justoverclock/custom-html-widget` and it happens to me in both) it would be nice to add a separate div for the title like in the Afrux ones with `div.AfruxWidgets-Widget-title`, because otherwise content padding is applied to everything, and if for example I want to add a bottom border to the title it looks like this:

With `div.AfruxWidgets-Widget-title`:

![Screenshot 2021-12-07 145907](https://user-images.githubusercontent.com/15818451/145043531-0a02008d-32a1-44f6-a353-09de750eaedb.png)

Without:

![Screenshot 2021-12-07 145850](https://user-images.githubusercontent.com/15818451/145043559-37604e05-1b2f-425a-9de9-21fadd90701f.png)

**Comment by justoverclockl** [comment]
i will fix this too

**Comment by justoverclockl** [comment]
wait..last registered user does not use `title()`, can i add just a separate div for the actual one?

because now i have a separate div:

```
<div class="welcomeText">
                    <p class="welcomeText">{app.translator.trans('justoverclock-last-registered-users.forum.welcomeText') + ': '}</p>
                </div>
```

**Comment by iamdarkle** [comment]
Sorry, I see what's going on, when I saw this I thought the div didn't exist:

![Screenshot 2021-12-07 170813](https://user-images.githubusercontent.com/15818451/145067224-b14975b6-8750-4f0e-bd99-e606497e1d0d.png)

To the right is yours, but it's simply built differently inside the content div, so by adding a bit of CSS you can get to the desired solution, in my case 

```
div.lastRegUser-widget > div {padding:0!important;}
div.lastRegUser-widget > div > div > div > ul {padding:15px!important;}
```

So I'm not sure if you want to change it or leave it as it is, knowing this I'm fine with it, it's a matter of personal customization.
